apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ include "demo-e2e.namespace" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
{{- if .Values.imagePullSecrets }}
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- else }}
        []
{{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ include "demo-e2e.namespace" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
