apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
  namespace: {{ include "demo-e2e.namespace" . }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
